#!/usr/bin/env python3
"""The Log's setup check (the owner's order in the pilot run: verify each chat's documents were built and
appended in, and that the chats can message each other). Paths come from SEATS_ROOT and SEATS_CONTEXT.
Reads each chats/<chat>/SETUP.md, its versioned snapshots, and the Log's captured events.
Writes chats/log/SETUP-CHECK.md."""
import glob, os, re, datetime as dt
NORM = os.path.join(os.path.abspath(os.environ.get("SEATS_ROOT") or os.getcwd()), os.environ.get("SEATS_CONTEXT", "context"))
RING = ["Scope", "Specifics", "Chain", "Research", "Vet", "Verify", "Refute", "Skills"]
rows = []
for i, chat in enumerate(RING):
    f = chat.lower()
    p = os.path.join(NORM, "chats", f, "SETUP.md")
    nxt, prv = RING[(i + 1) % 8], RING[i - 1]
    text = open(p, encoding="utf-8", errors="replace").read() if os.path.exists(p) else ""
    versions = len(glob.glob(os.path.join(NORM, "chats", "log", "snapshots", f, "SETUP@*.md")))
    saw = re.findall(r"\b(\d)\s*/\s*9\b", text)
    sent = bool(re.search(rf"ping[^\n]*(sent|to)[^\n]*{nxt}", text, re.I))
    got = bool(re.search(rf"ping received from {prv}", text, re.I))
    docs = sorted(os.path.basename(x) for x in glob.glob(os.path.join(NORM, "chats", f, "*.md")))
    rows.append((chat, "yes" if text else "MISSING", versions, saw[-1] + "/9" if saw else "?", nxt, "yes" if sent else "not recorded",
                 prv, "yes" if got else "not yet", ", ".join(docs)))
now = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
out = [f"# Setup check\n\nRegenerated by `chats/log/setup_check.py`. Last run {now}. It reads each chat's own SETUP.md; the ring is Scope → Specifics → Chain → Research → Vet → Verify → Refute → Skills → Scope.\n",
       "| chat | SETUP.md | versions snapshotted | names seen | ping sent to | sent recorded | ping expected from | received recorded | documents in its folder |",
       "|---|---|---|---|---|---|---|---|---|"]
out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
open(os.path.join(NORM, "chats", "log", "SETUP-CHECK.md"), "w").write("\n".join(out) + "\n")
print("\n".join(out[1:]))
